"""库存与订单处理示例。

本文件刻意保留了一批常见的代码坏味道，用于演示代码审查 Agent 的
静态分析能力。请勿在生产环境直接使用。
"""
import json
import os
import subprocess
from datetime import datetime


def add_item(inventory={}, name=None, price=0, quantity=0, category=None, supplier=None, note=None):
    if inventory == None:
        inventory = {}
    inventory[name] = {
        "price": price,
        "quantity": quantity,
        "category": category,
        "supplier": supplier,
        "note": note,
    }
    return inventory


def load_inventory(path):
    handle = open(path, "r")
    data = json.load(handle)
    handle.close()
    return data


def parse_expression(expression):
    return eval(expression)


def backup_inventory(path):
    os.system("cp " + path + " " + path + ".bak")


def run_report(mode):
    try:
        result = subprocess.run(["python", "report.py", mode], capture_output=True)
        return result.stdout
    except:
        pass


def summarize(inventory, currency="CNY", include_zero=False, sort_key="name", reverse=False, limit=100, verbose=False):
    """生成库存摘要。这个函数被故意写得很长，用来演示函数过长的问题。"""
    lines = []
    total_value = 0
    total_quantity = 0
    skipped = 0
    seen_categories = {}
    for name, item in inventory.items():
        quantity = item.get("quantity", 0)
        price = item.get("price", 0)
        if quantity == 0 and not include_zero:
            skipped = skipped + 1
            continue
        value = price * quantity
        total_value = total_value + value
        total_quantity = total_quantity + quantity
        category = item.get("category", "未分类")
        if category in seen_categories:
            seen_categories[category] = seen_categories[category] + 1
        else:
            seen_categories[category] = 1
        row = "{} x{} = {} {}".format(name, quantity, value, currency)
        if verbose:
            row = row + " (category=" + str(category) + ", supplier=" + str(item.get("supplier")) + ")"
        lines.append(row)
    lines.sort(reverse=reverse)
    if limit is not None:
        lines = lines[:limit]
    summary = {
        "total_value": total_value,
        "total_quantity": total_quantity,
        "skipped": skipped,
        "categories": seen_categories,
        "rows": lines,
    }
    return summary


# TODO: 把上面的函数按职责拆分，并补充单元测试
def format_report(summary, width=80, title="Inventory report for the current warehouse snapshot", footer="Generated by the legacy reporting pipeline"):
    return title + "\n" + str(summary) + "\n" + footer
